import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import Head from 'next/head'

const articles = () => {
    return (
        <>
            <Navbar />
            <Head>
                <title>Blocksoc | Articles</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="Blocksoc" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="title-text text-dynamic mt-4">Articles</h1>
            <Layout>

                <p className="max-w-[70ch] mx-auto text-center text-lg">
                    The CEF is a research-based forum that seeks to analyse crypto
                    assets based on sound principles, including consensus mechanisms, tokenomics and much more...
                </p>
            </Layout>
        </>

    )
}

export default articles;