import Head from 'next/head'
import Contact from '../components/Contact'
import Navbar from '../components/Navbar'
import HeroSection from '../components/Hero'
import Offerings from '../components/Offerings'


export default function Home() {

  return (
    <div className='Container'>
      <Head>
        <title>Blocksoc</title>
        <meta name="google-site-verification" content="6ScdAOOBeybqZCJ11P1i-70LolkGwkbrgenM2RrtJLY" />
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Blocksoc" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <HeroSection />
        <Offerings />
        <Contact />
      </main>

    </div>
  )
}
