import Navbar from "../components/Navbar"
import styles from '../styles/positionpage.module.css'
import Head from 'next/head'
import Layout from "../components/Layout"


const jointheteam = () => {
    return (
        <>
            <Navbar />
            <Layout>
                <Head>
                    <title>Blocksoc | Positions</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="description" content="Blocksoc" />
                    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <p className={styles.heading}>
                    The CEF is a research-based forum that seeks to analyse crypto
                    assets based on sound principles, including consensus mechanisms, tokenomics and much more...
                </p>
                <div className={styles.roles}>
                    <details>
                        <summary>
                            Treasurer
                        </summary>
                        <div className={styles.content}>
                            <p>- General Financial Oversight, Financial Planning &amp; Budgeting, Financial Reporting, Banking, Bookkeeping &amp; Record Keeping.</p>
                            <p>- Prior experience is preferable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Head of Marketing
                        </summary>
                        <div className={styles.content}>
                            <p>- Coordination of all marketing, public relations and branding.</p>
                            <p>- Coordination of Social Media Strategies.</p>
                            <p>- Management of Social Media Accounts.</p>
                            <p>- Working with relevant departments & event coordinators to ensure effective promotion.</p>
                            <p>- Coordinate sponsor requests for promotion with the Head of Sponsorship.</p>
                            <p>- Coordination of the Graphic Designer, Content Curators, Media Producer, Photographer &amp; Videographer for the production of content.</p>
                            <p>- Prior experience is preferable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Graphic Designer
                        </summary>
                        <div className={styles.content}>
                            <p>- Providing graphic design expertise primarily in coordination with the Marketing team but also to other departments of the organisation if required.</p>
                            <p>- Create informative and attention grabbing social media content.</p>
                            <p>- Experience with design tools such as Figma or Adobe Xd.</p>
                            <p>- Prior experience is preferable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Content Curator
                        </summary>
                        <div className={styles.content}>
                            <p>- The production &amp; review of all content for all digital platforms. (e.g. social media platforms, website &amp; Blog).</p>
                            <p>- A high level of english &amp; familiarity with the Blockchain space are desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Media Producer
                        </summary>
                        <div className={styles.content}>
                            <p>- The production of videos for the purpose of promotion or education.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Photographer
                        </summary>
                        <div className={styles.content}>
                            <p>- Photography of events hosted by BlockSoc.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Videographer
                        </summary>
                        <div className={styles.content}>
                            <p>- The videoing of virtual and F2F events for the purpose of promotion.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Head of Sponsorship
                        </summary>
                        <div className={styles.content}>
                            <p>- Responsible for leading the sponsorship team in attaining sponsorship & catering to the needs of onboarded sponsors.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Sponsorship Officer
                        </summary>
                        <div className={styles.content}>
                            <p>- The Sponsorship Officer will support the Head of Sponsorship in attaining sponsorship & catering to the needs of onboarded sponsors.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Head of Event Management
                        </summary>
                        <div className={styles.content}>
                            <p>- Primarily responsible for the organisation and coordination of BlockSoc’s events.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Event Management Officers
                        </summary>
                        <div className={styles.content}>
                            <p>- Responsible for assisting the Head of Event Management in the organisation and coordination of BlockSoc’s events.</p>
                            <p>- Prior experience is desirable.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Head of Women in Blockchain
                        </summary>
                        <div className={styles.content}>
                            <p>- The Head of Women in Blockchain will be responsible for promoting & heading our Women in Blockchain initiative. They will be primarily involved in directing educational content &amp; guest speakers for the Women in Blockchain program.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Domain Experts *** Need Clairifcation
                        </summary>
                        <div className={styles.content}>
                            <p>- Directing educational content concerning their domain.</p>
                            <p>- Running educational workshops concerning their domain.</p>
                            <p>- Acting as an advisor to the Cryptoasset Evaluation Forum regarding their particular domain.</p>
                            <p>- Co-hosting guest speakers from their domain.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Campus Officers
                        </summary>
                        <div className={styles.content}>
                            <p>- We are expanding our presence across third level institutions in Ireland and are
                                looking to recruit students from such institutions to assist with this expansion.
                                We hope to have a campus officer for each third level institution. The campus officer will assist
                                with all matters concerning BlockSoc’s expansion into their institution.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>
                    <details>
                        <summary>
                            Campus Ambassadors
                        </summary>
                        <div className={styles.content}>
                            <p>- A campus ambassador will be responsible for promoting BlockSoc in their respective institution.</p>
                            <p><a href="/">Apply Here</a></p>
                        </div>
                    </details>

                </div>
            </Layout>
        </>
    )
}

export default jointheteam
