import Navbar from "../components/Navbar"
import styles from '../styles/positionpage.module.css'
import Head from 'next/head'


const jointheteam = () => {
    return (
        <>
            <Head>
                <title>Blocksoc | Positions</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="Blocksoc" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={styles.container}>
                <h1>Coming soon!</h1>
                <p>Be sure to keep an eye on our socials for updates.</p>
            </div>
        </>
    )
}

export default jointheteam
