import Layout from "../components/Layout";
import Navbar from "../components/Navbar";
import Head from 'next/head'

const startathon = () => {
    return (
        <>
            <Head>
                <title>Blocksoc | Startathon</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="Blocksoc" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Layout />
            <h1>Startathon</h1>
        </>

    )
}

export default startathon;